# Generated by Django 3.2.8 on 2021-10-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
