# Generated by Django 3.2.8 on 2021-10-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='name',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='phone',
        ),
    ]
