# Generated by Django 3.2.8 on 2021-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbook',
            options={'verbose_name': 'ความคิดเห็นของผู้ชม', 'verbose_name_plural': 'ความคิดเห็นของผู้ชม'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('name',), 'verbose_name': 'บทความ', 'verbose_name_plural': 'ข้อมูลบทความ'},
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
