# Generated by Django 3.2.8 on 2021-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20211025_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guestbook',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
